core/urls.py
from django.urls import path
from .views import home,usuario_creado, listado_libros, form_libro, form_mod_libro, form_eli_libro, form_reg_usuario

urlpatterns = [
    path('', home,name="home"),
    path('usuario-creado', usuario_creado, name="usuario_creado"),
    path('listado-libros', listado_libros, name="listado_libros"),
    path('form-libro', form_libro, name="form_libro"),
    path('form-mod-libro/<id>', form_mod_libro, name="form_mod_libro"),
    path('form-eli-libro/<id>', form_eli_libro, name="form_eli_libro"),
    path('form-reg-usuario', form_reg_usuario, name="form_reg_usuario"), 
]

website/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls'))
]

core/models.py
from django.db import models

# Create your models here.

class Categoria(models.Model):
    idCategoria =models.IntegerField(primary_key=True, verbose_name='Id de Categoria')
    nombreCategoria =models.CharField(max_length=50, verbose_name='Nombre de la Categoria')

    def __str__(self):
        return self.nombreCategoria
   
class Libro(models.Model):
    ISBN =models.CharField(max_length=13, primary_key=True, verbose_name='ISBN')        
    nombreLibro =models.CharField(max_length=50, verbose_name='Nombre del Libro')
    autor =models.CharField(max_length=75, verbose_name='Autor')
    descripcion =models.CharField(max_length=250, null=True, blank=True, verbose_name='Descripcion')
    categoria =models.ForeignKey(Categoria, on_delete=models.CASCADE)

    def __str__(self):
        return self.ISBN

class Usuario(models.Model):
    correo = models.CharField(primary_key=True, max_length=75, verbose_name='Correo de Usuario')
    nombre = models.CharField(max_length=25, verbose_name='Nombre de Usuario')
    password = models.CharField(max_length=12, verbose_name='Contraseña')
    repeatPassword = models.CharField(max_length=12, verbose_name='Repetir Contraseña')
    comentario = models.TextField(max_length=250, verbose_name='Comentario')

    def __str__(self):
        return self.correo         

core/forms.py
from django import forms
from django.db.models import fields
from django.forms import ModelForm
from .models import Libro, Usuario

class LibroForm(ModelForm):
    ISBN = forms.CharField(label='ISBN',widget=forms.TextInput(attrs={"placeholder": "13 dígitos"}))
    autor = forms.CharField(label='Autor')
    nombreLibro = forms.CharField(label='Nombre Libro')
    descripcion = forms.CharField(label='Descripción')
    
    class Meta:
        model = Libro
        fields = ['ISBN','nombreLibro', 'autor', 'descripcion','categoria',]
    
class RegistroUsuarioForm(ModelForm):
    correo = forms.CharField(label='E-mail')
    nombre = forms.CharField(label='Nombre')
    password = forms.CharField(label='Contraseña', widget=forms.PasswordInput(attrs={"placeholder": "************"}))
    repeatPassword = forms.CharField(label='Repita su Contraseña', widget=forms.PasswordInput(attrs={"placeholder": "************"}))
    
    class Meta:
        model = Usuario
        fields = ['correo', 'nombre', 'password', 'repeatPassword','comentario',]

core/views.py
from django.shortcuts import render, redirect
from.models import Libro, Usuario
from .forms import LibroForm, RegistroUsuarioForm
from django.contrib import messages
from django.core.exceptions import ValidationError
 
# Create your views here.

def home(request):
    return render(request, 'core/home.html')

def listado_libros(request):
    libros = Libro.objects.all()
    datos = {
        'libros': libros
     }
    return render(request, 'core/listado_libros.html', datos)

def usuario_creado(request):
    return render(request, 'core/usuario_creado.html')    

def form_libro(request):
    datos = {
        'form': LibroForm()
    }
    if request.method == 'POST':
        formulario = LibroForm(request.POST)
        if formulario.is_valid():
            formulario.save()
            formulario = LibroForm()
            messages.add_message(request, messages.INFO, 'Registro Creado Correctamente.')
            return  redirect(to="listado_libros")
        else:
            datos['mensaje'] = "ISBN Incorrecto"
    return render(request, 'core/form_libro.html', datos)

def form_mod_libro(request, id):
    libro = Libro.objects.get(ISBN=id)
    datos = {
        'form': LibroForm(instance=libro)
    }
    if request.method == 'POST':
        formulario = LibroForm(data=request.POST, instance=libro)
        if formulario.is_valid:
            formulario.save()
            messages.add_message(request, messages.INFO, 'Registro Modificado Correctamente.')
            return  redirect(to="listado_libros")
    return render(request, 'core/form_mod_libro.html', datos)    

def form_eli_libro(request, id):
    libro = Libro.objects.get(ISBN=id)
    libro.delete()
    messages.add_message(request, messages.INFO, 'Registro Eliminado Correctamente.')
    return redirect(to="listado_libros")    

def form_reg_usuario(request):
    datos = {
        'form': RegistroUsuarioForm()
    }
    if request.method == 'POST':
        formulario = RegistroUsuarioForm(request.POST)
        if formulario.is_valid():
            formulario.save()
            formulario = RegistroUsuarioForm()
            datos['mensaje'] = "Datos Ingresados correctamente"
            return redirect(to="usuario_creado")
        else:
            datos['mensaje'] = "Ya se ha registrado anteriormente con este Correo Electronico, pruebe con otro."
    return render(request, 'core/form_reg_usuario.html', datos)

core/templates/core/base.html
<!doctype html>
<html lang="es">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <!-- CSS only -->
    {% load static %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'core/css/style.css'%}">
    <title>{% block title %}{% endblock title %}</title>
    <link rel="shortcut icon" href="{% static 'core/img/Icono_hogwarts.png' %}">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="{% static 'core/js/validacion.js'%}"></script>

</head>

<body>

    <!--Inicio Barra de Navegación-->

    <nav class="navbar navbar-expand-lg navbar-light bg-light" id="barra">
        <div class="container-fluid">
            {% load static %}
            <a class="navbar-brand" href="{% url 'home' %}"><img src="{% static 'core/img/Icono_hogwarts.png' %}"
                    id="logo"></a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'home' %}">Inicio</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'form_reg_usuario' %}">Registro de Usuario</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'listado_libros' %}">Listado de Libros</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

    <!--Fin Barra de Navegación-->

    <!--Inicio Django-->
    {% block content %}

    {% endblock content %}
    <!--Fin Django-->


    <!--Inicio Footer-->

    <hr>

    <div class="footer-basic">
        <footer>

            <p class="copyright">Libreria "Hogwarts" © 2021 || <a>Todos los derechos reservados </a> </p>

        </footer>
    </div>

    <!--Fin Footer-->


    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/js/bootstrap.bundle.min.js"></script>

    <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns"
        crossorigin="anonymous"></script>


    <script>

        $("#id_ISBN").inputFilter(function (value) {
            return /^\d*$/.test(value);
        });

    </script>

    <script>
        $("#enviar").click(function () {

            var codigo = $("#id_ISBN").val();
            var nombreLibro = $("#id_nombreLibro").val();
            var autor = $("#id_autor").val();
            var descripcion = $("#id_descripcion").val();
            var categoria = $("#id_categoria").val();

            var mensaje = "";

            if (codigo !== "") {
                if (codigo.length !== 13) {
                    mensaje += "Valide que el ISBN contenga 13 digitos!\n";
                }

            } else {
                mensaje += "Ingrese ISBN \n";
            }

            if (nombreLibro == "") {
                mensaje += "Ingrese el Nombre del libro \n";
            }

            if (autor == "") {
                mensaje += "Ingrese el Autor \n";
            }

            if (descripcion == "") {
                mensaje += "Ingrese la descripcion \n";
            }

            if (categoria == "") {
                mensaje += "Seleccione la categoria \n";
            }

            if (mensaje !== "") {
                alert(mensaje);
                return false;
            }

        });

    </script>

    <script>

        $("#enviarUsuario").click(function () {

            var nombre = $("#id_nombre").val();
            var correo = $("#id_correo").val();
            var comentario = $("#id_comentario").val();
            var contraseña = $("#id_password").val();
            var repeatContraseña = $("#id_repeatPassword").val();

            var mensaje = "";

            if (nombre == "") {
                mensaje += "Ingrese Nombre \n";
            }

            if (correo == "") {
                mensaje += "Ingrese Email \n";
            } else {
                var validaFormatoCorreo = correoValido(correo);
                if (validaFormatoCorreo == false) {
                    mensaje += "Formato de email invalido, corríjalo e intente nuevamente!\n";
                }
            }

            if (contraseña == "") {
                mensaje += "Ingrese Contraseña \n";
            }

            if (repeatContraseña == "") {
                mensaje += "Repita su contraseña \n";
            }

            if (contraseña !== repeatContraseña) {
                mensaje += "Las Contraseñas no son iguales, corríjalas e intente nuevamente! \n";
            }

            if (comentario == "") {
                mensaje += "Ingrese Comentario \n";
            }

            if (mensaje !== "") {
                alert(mensaje);
                return false;
            }

            function correoValido(correo) {
                var caract = new RegExp(/^(([^<>()[\]\.,;:\s@\"]+(\.[^<>()[\]\.,;:\s@\"]+)*)|(\".+\"))@(([^<>()[\]\.,;:\s@\"]+\.)+[^<>()[\]\.,;:\s@\"]{2,})$/i);
                if (caract.test(correo) == false) {
                    return false;
                } else {
                    return true;
                }
            }
            
        });

    </script>

    });

</body>

</html>

core/templates/core/form_libro.html
{% extends "core/base.html" %}form_libro

{% block title %}Registrar Libro{% endblock title %}

{% block content %}
{% load static %}
<div class="container mt-1 mb-1 align_self">
    <div class="d-flex justify-content-center">
        <h1>Registrar Libro</h1>
    </div>
    <div class="d-flex justify-content-center">
        <form action="" method="post" id="form_libro">
            {% csrf_token %}
            <div class="form-group">
                {{ form.as_table }}
            </div>
            
            <hr>

            <div class="d-flex justify-content-center">
                <input type="submit" value="Enviar" class="btn btn-danger" id="enviar" alt="boton" >
            </div>

        </form>
    </div>

</div>
{% endblock content %}

core/templates/core/form_mod_libro.html
{% extends "core/base.html" %}

{% block title %}Modificar Libro{% endblock title %}

{% block content %}
{% load static %}
<div class="container mt-1 mb-1 align_self">
    <div class="d-flex justify-content-center">
        <h1>Modificar Libro</h1>
    </div>
    <div class="d-flex justify-content-center">
        <form action="" method="post" id="form_libro">
            {% csrf_token %}
            <div class="form-group">
                {{ form.as_table }}
            </div>

            <hr>

            <div class="d-flex justify-content-center">
                <div class="button">
                    <input type="submit" value="Modificar" class="btn btn-success" id="enviar" alt="boton">
                </div>
            </div>

        </form>
    </div>
    <div role="alert">{{mensaje}}</div>
</div>
{% endblock content %}

core/templates/core/form_reg_usuario.html
{% extends "core/base.html" %}

{% block title %}Registro de Usuario{% endblock title %}

{% block content %}
{% load static %}
<div class="container mt-1 mb-1 align_self">

    <div class="d-flex justify-content-center">
        <h1>Registro de Usuario</h1>
    </div>
    <div class="d-flex justify-content-center">
        <form action="" method="post" id="form_libro">
            {% csrf_token %}
            <div class="form-group">
                {{ form.as_p }}
            </div>
    </div>

    <hr>

    <div class="d-flex justify-content-center">
        <input type="submit" value="Enviar" class="btn btn-success" id="enviarUsuario" alt="boton">
    </div>
    </form>
</div>

<div class="d-flex justify-content-center" role="alert">{{mensaje}}</div>

{% endblock content %}

core/templates/core/home.html
{% extends "core/base.html" %}

{% block title %}Libreria Hogwarts{% endblock title %}

{% block content %}
    <div class="container mt-1 mb-1">
        <div class="d-flex justify-content-center">
            <h1>Bienvenidos a la Libreria Hogwarts</h1>
        </div>
        <div class="d-flex justify-content-center">
            <p>Aqui podras encontrar todos tus libros favoritos y si no lo tenemos, lo buscaremos para ti!</p>
        </div>
        <div id="carouselExampleCaptions" class="carousel slide" data-ride="carousel">
            <ol class="carousel-indicators">
                <li data-target="#carouselExampleCaptions" data-slide-to="0" class="active"></li>
                <li data-target="#carouselExampleCaptions" data-slide-to="1"></li>
                <li data-target="#carouselExampleCaptions" data-slide-to="2"></li>
            </ol>
            {% load static %}
            <div class="carousel-inner">
                <div class="carousel-item active">
                    <a title="carrusel1">
                        <img src="{% static 'core/img/prisionero.jpg' %}" id="img_carr" class="d-block w-100" alt="carrusel"></a>
                    <div class="carousel-caption d-none d-md-block">
                    </div>
                </div>
                <div class="carousel-item">
                    <a title="carrusel2">
                        <img src="{% static 'core/img/sorcerer.jpg' %}" id="img_carr" class="d-block w-100" alt="carrusel"></a>
                    <div class="carousel-caption d-none d-md-block">
                    </div>
                </div>
                <div class="carousel-item">
                    <a title="carrusel3">
                        <img src="{% static 'core/img/piedra_filosofal.jpg' %}" id="img_carr" class="d-block w-100" alt="carrusel"></a>
                    <div class="carousel-caption d-none d-md-block">
                    </div>
                </div>
            </div>
            <a class="carousel-control-prev" href="#carouselExampleCaptions" role="button" data-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="sr-only"></span>
            </a>
            <a class="carousel-control-next" href="#carouselExampleCaptions" role="button" data-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="sr-only"></span>
            </a>
        </div>

        <div class="d-flex justify-content-center">
            <p>Disfruta de nuestro catalogo y sumate a esta gran comunidad!</p>
        </div>

    </div>
{% endblock content %}

core/templates/core/listado_libros.html
{% extends "core/base.html" %}

{% block title %}Listado de Libros{% endblock title %}

{% block content %}
{% load static %}
<div class="container mt-1 mb-1 align_self">
    <div class="d-flex justify-content-center">
        <h1>Listado de Libros</h1>
    </div>
    <div class="d-flex justify-content-center">
        <div class="table-responsive">
            <table class="table align-middle">
                <thead>
                    <tr>
                        <th scope="col">ISBN</th>
                        <th scope="col">Nombre</th>
                        <th scope="col">Autor</th>
                        <th scope="col">Descripción</th>
                        <th scope="col">Opciones</th>
                    </tr>
                </thead>
                <tbody>
                    {% for li in libros %}
                    <tr>
                        <td>{{li.ISBN}}</td>
                        <td>{{li.nombreLibro}}</td>
                        <td>{{li.autor}}</td>
                        <td>{{li.descripcion}}</td>
                        <td><a href="{% url 'form_mod_libro' li.ISBN %}"><img
                                    src="{% static 'core/img/Icono_modificar.svg'%}" alt="Modificar" id="opc_img" /></a>

                            <a href="{% url 'form_eli_libro' li.ISBN %}"><img
                                    src="{% static 'core/img/Icono_eliminar.svg'%}" alt="Eliminar" id="opc_img" /></a>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
            {% if messages %}
            <ul class="messages">
                {% for message in messages %}
                <li{% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</li>
                    {% endfor %}
            </ul>
            {% endif %}
        </div>
    </div>

    <hr>

    <div class="d-flex justify-content-center">
        <a class="btn btn-success" href="{% url 'form_libro' %}" id="boton">Nuevo registro</a>
    </div>
</div>
{% endblock content %}

core/templates/core/usuario_creado.html
{% extends "core/base.html" %}

{% block title %}Bienvenida Usuario{% endblock title %}

{% block content %}
{% load static %}
<div class="container mt-1 mb-1 align_self">    
    <div class="d-flex justify-content-center">
        <img src="{% static 'core/img/Icono_usuario.svg' %}" alt="" id="img_user">
    </div>
    <div class="d-flex justify-content-center">
        <h1 style="text-align: center;"> Usuario Creado Correctamente</h1>
    </div>
    <div class="d-flex justify-content-center">
        <a href="{% url 'home' %}" class="btn btn-success" role="button" aria-pressed="true" id="boton">Volver al Inicio </a>
        <a href="{% url 'form_reg_usuario' %}" class="btn btn-success" role="button" aria-pressed="true" id="boton">Registrar otro Usuario</a>
    </div>
</div>



{% endblock content %}